# Generated by Django 2.1.2 on 2018-10-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20181029_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='perduct',
            name='s33',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
